# Generated by Django 3.1.3 on 2020-11-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('number_of_page', models.IntegerField()),
                ('stock_quantity', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraryapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now=True)),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.book')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_year', models.CharField(choices=[(1, 'First year'), (2, 'Second year'), (3, 'Third year'), (4, 'Forth year')], default=1, max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('books', models.ManyToManyField(through='libraryapp.Borrow', to='libraryapp.Book')),
            ],
        ),
        migrations.AddField(
            model_name='borrow',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.student'),
        ),
    ]
