# Generated by Django 3.1.3 on 2020-11-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_year',
            field=models.IntegerField(choices=[(1, 'First year'), (2, 'Second year'), (3, 'Third year'), (4, 'Forth year')], default=1, max_length=10),
        ),
    ]
