# Generated by Django 3.1.3 on 2020-11-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_auto_20201114_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_year',
            field=models.IntegerField(choices=[(1, 'First year'), (2, 'Second year'), (3, 'Third year'), (4, 'Forth year')], default=1),
        ),
    ]
